adding auto doc generation into testing, trying it out on 1.3M_ms_high_Z

diff --git a/star/test_suite/each_test_run b/star/test_suite/each_test_run
--- a/star/test_suite/each_test_run
+++ b/star/test_suite/each_test_run
@@ -17,6 +17,40 @@ function testhub_log {
     echo "$1" >> testhub.yml
 }
 
+# Optional function to update the docs after a test has passed.
+# This function checks for images specified in the problem's README.rst file
+# and copies images generated by the run to the appropriate location in the docs,
+# otherwise it generates an error message
+function update_docs {
+    # check for images in README.rst
+    if grep -q ".. image::" README.rst; then
+        # copy images to docs if it exists
+        for img in $(grep ".. image::" README.rst | cut -d' ' -f3); do
+            filename=$(basename -- "$img")
+            extension="${filename##*.}"
+            filename="${filename%.*}"
+            echo "$filename"
+            echo "$extension"
+        done
+        for img in $(grep ".. image::" README.rst | cut -d' ' -f3); do
+            filename=$(basename -- "$img")
+            extension="${filename##*.}"
+            filename="${filename%.*}"
+            image_to_copy="$extension/$filename.$extension"
+            if [ -e "$image_to_copy" ]; then
+                cp "$image_to_copy" docs/
+                echo "Updated image $filename.$extension in the docs"
+                # replace the line "Last-Updated: ..." in README.rst
+                sed -i "" "s/Last-Updated: .*/Last-Updated: $(date '+%d%b%Y') (MESA $(git rev-parse --short HEAD)) by $USER/" README.rst
+            else
+                echo "Error: $image_to_copy not found. Test may no longer be producing this file or may now be producing a different final snapshot number! Update test and README.rst accordingly."
+            fi
+        done
+    else
+        echo "(no images found in README.rst)"
+    fi
+}
+
 # remove known false positive messages from stderr output file (err.txt)
 function filter_stderr {
     cp err.txt err.tmp
@@ -228,6 +262,11 @@ function build_and_run {
 
     # if we made it this far, we passed
     testhub_log "outcome: :pass"
+
+    # if we're updating the docs, try to do it here
+    if [ "$has_update_docs_flag" = true ]; then
+        update_docs
+    fi
     return
 
 }
@@ -275,6 +314,21 @@ fi
 
 }
 
+# check for '--update-docs' optional flag
+has_update_docs_flag=false
+for i in "$@"; do
+  case $i in
+    -u|--update-docs)
+      has_update_docs_flag=true
+      echo "(updating docs after successful test runs)"
+      shift # past argument with no value
+      ;;
+    -*|--*)
+      echo "Unknown option $i"
+      exit 1
+      ;;
+  esac
+done
 
 date
 echo ""
