hopefully have fixed the problems with old scripts in rsp_save_and_load

diff --git a/star/test_suite/rsp_save_and_load_file/re b/star/test_suite/rsp_save_and_load_file/re
--- a/star/test_suite/rsp_save_and_load_file/re
+++ b/star/test_suite/rsp_save_and_load_file/re
@@ -1,13 +1,31 @@
 #!/bin/bash
 
-function check_okay {
-	if [ $? -ne 0 ]
-	then
-		exit 1
-	fi
+photo_directory=photos
+
+function most_recent_photo {
+    ls -t "$photo_directory" | head -1
 }
 
-echo $1
-cp photos/$1 restart_photo
-check_okay
-date;./star;date
+if [ $# -eq 0 ]
+then
+    photo=$(most_recent_photo)
+else
+    photo=$1
+fi
+
+if [ -z "$photo" ] || ! [ -f "$photo_directory/$photo" ]
+then
+    echo "specified photo does not exist"
+    exit 1
+fi
+
+echo "restart from $photo"
+if ! cp "$photo_directory/$photo" restart_photo
+then
+    echo "failed to copy photo"
+    exit 1
+fi
+
+date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
+./star
+date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
