Features/nialljmiller/customcolors update0 (#909)
* [ci skip] minor change to python helper so different filters work.

* [ci skip] readme updates, still WIP

* [ci skip] new python visualisations for interpolation distance

* added interpolation radius to allow for quality checks in custom colors + added select case for those wishing to change interpolation method -- this still needs to be piped to a user option

* [ci skip] updating python helpers now so later commit is easier

* [ci skip] added zero point defined by user]

* [ci skip] added user defined zero point

* [ci skip]
 updating colors data file

* [ci skip] WIP README, new format and overview.

* [ci skip] changed defaults to Johnson UBVRI

* readme update

* [ci skip] pulling updates

* [ci skip] Update distance value in colors.defaults to 10pc

* [ci skip] cleaning

* [ci skip] pg star

* [ci skip] inlists

* [ci skip] updated defaults

* [ci skip] make_CMD_InterpRad_movie.py

* Update README.rst

* Update README.rst

* [ci skip] Enhance README with parameter examples

Added examples for various parameters in README.

* [ci skip] added management for missing columns in stellar atm tables

* [ci skip] inlist update

* Update README.rst

* Enhance README with test suite details and usage

Expanded the README to include detailed descriptions of the test suite's functionality, output, and purpose. Added sections on real-time visualization and inlist options.

* Create README.rst

* [ci skip] removed old python helpers from /colors/ as they are now deprecated with https://github.com/nialljmiller/SED_Tools

* cleaning for merge

* lintinh

* adding new colors data

* fortitude check --fix

* ruff check on python files

* added some pg star windows

* change colors test termination condition

* make sure to save final.mod in colors testing

* add final modl name

* fixing bug found in usage of clight where the wrong units were assumed for AB zeropoint. Also fixed Vega zero point interpolation error.

* [ci skip] cleaning files

* built with SDK 25.12.1

* moved colors data from colors/data to data/colors_data

* [ci skip] Added more files for moving the data.

* [ci skip] removing junk

* [ci skip] removing file io junk

* [ci skip] updates on file io operations. zero points are calculated at initilisation and SED tables are cached at initialiation.

* [ci skip] updates for history files and python helpers

* fixed inlist

* Python linting

* Python linting

* Apply suggestions from code review

removing unnecessary redefine of dp.

Co-authored-by: Warrick Ball <W.H.Ball@bham.ac.uk>

* [ci skip] docs linting

---------

Co-authored-by: pmocz <philip.mocz@gmail.com>
Co-authored-by: Warrick Ball <W.H.Ball@bham.ac.uk>

diff --git a/colors/build_data_and_export b/colors/build_data_and_export
--- a/colors/build_data_and_export
+++ b/colors/build_data_and_export
@@ -10,8 +10,8 @@ function check_okay {
 }
 
 # Create working directory
-mkdir -p data
-cd data
+mkdir -p ../data/colors_data
+cd ../data/colors_data
 
 # Variables
 ARCHIVE_NAME="colors_data.txz"
@@ -29,16 +29,20 @@ if [ ! -f "$EXTRACTED_FLAG" ]; then
     # If the archive is missing
     if [ ! -f "$ARCHIVE_NAME" ]; then
         echo "Archive $ARCHIVE_NAME is missing."
-        echo "Please ensure it is downloaded or available in this directory."
+        echo "Please ensure $ARCHIVE_NAME is downloaded or available in this directory."
         # it should now auto-download from a LFS pointer... i think?
-
-        exit 1
+        git -C "$MESA_DIR" lfs pull --include="data/colors_data/colors_data.txz"   #like this
+        
+        if [ ! -f "$ARCHIVE_NAME" ]; then
+            echo "Archive $ARCHIVE_NAME is still missing."
+            exit 1
+        fi
     fi
 
     # Validate it
     if ! validate_archive; then
         echo "Archive $ARCHIVE_NAME is invalid."
-        # try again to download or something?
+        git -C "$MESA_DIR" lfs pull --include="data/colors_data/colors_data.txz"   #and again...
 
         # Validate it
         if ! validate_archive; then
