Unify ck scripts in utils and module tests

diff --git a/utils/test/ck b/utils/test/ck
--- a/utils/test/ck
+++ b/utils/test/ck
@@ -1,1 +1,10 @@
-./../../utils/test/ck6
+#!/bin/bash
+
+if ./rn >& tmp.txt; then
+    diff -b tmp.txt test_output
+else
+    echo
+    echo "FAILED"
+    echo
+    exit 1
+fi
